
CREATE TABLE IF NOT EXISTS roles ( id SERIAL PRIMARY KEY, nombre VARCHAR(50) UNIQUE NOT NULL );
CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) NOT NULL,
  correo VARCHAR(150) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, id_rol INTEGER NOT NULL REFERENCES roles(id)
);
CREATE TABLE IF NOT EXISTS ofertas (
  id SERIAL PRIMARY KEY, id_empresa INTEGER NOT NULL REFERENCES usuarios(id),
  titulo VARCHAR(120) NOT NULL, descripcion TEXT NOT NULL, tipo_practica VARCHAR(50) NOT NULL DEFAULT 'Profesional',
  fecha_publicacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, estado VARCHAR(30) NOT NULL DEFAULT 'Activa'
);
CREATE TABLE IF NOT EXISTS postulaciones (
  id SERIAL PRIMARY KEY, id_estudiante INTEGER NOT NULL REFERENCES usuarios(id),
  id_oferta INTEGER NOT NULL REFERENCES ofertas(id), estado VARCHAR(30) NOT NULL DEFAULT 'Enviada',
  fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
